[features]
seeds = false
[programs.localnet]
netflix_clone = "B3LNGaKnMwGQ1XQRseRbQbEzc1FjbztHrqmbXHruGgfm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "devnet"
cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/start.ts"
